const translations = {
  zh: {
    pageTitle: "USDT转TRX、购买TRON能量｜快速、安全、可靠",
    toggleLang: "中文",
    desc: "即使你的TRX余额为0，也可以将USDT 兑换成TRX", 
    energy: "能量:",
    bandwidth: "带宽:",
    buyEnergy: "购买能量",
    flashExchange: "闪兑服务",
    addressLabel: "接收地址",
    connectWallet: "连接钱包获取地址",
    addressPlaceholder: "默认为当前账户地址",
    buyCount: "购买笔数",
    tip: "如对方无USDT，请购买2笔。",
    btn1: "1笔",
    btn2: "2笔",
    btn5: "5笔",
    btn10: "10笔",
    getEnergy: "获得能量",
    expireTip: "能量有效期<span class='text-orange'>24小时</span>",
    energyPlaceholder: "能量值",
    finalPriceText: "您只要支付 <span class='text-green-400' id='final_price'></span> 为您节省 <span class='text-gray-500 mr-2' id='origin_price'></span>",
    purchaseBtn: "购买能量",
    inputAmountPlaceholder: "请输入数量",
    outputAmountPlaceholder: "预计收到的数量",
    payText: "您只要支付",
    saveText: "为您节省",
    payLabel: "支付",
    receiveLabel: "接收",
    exchangeNow: "立即兑换",
    chooseWallet: "选择钱包",
    scanToLogin: "扫码登录",
    confirmOrder: "订单确认",
    paymentAddress: "支付地址：",
    receiveAddress: "接收地址：",
    energyAmount: "租用能量：",
    paymentAmount: "支付金额：",
    confirmPay: "支付",
    cancel: "取消",
    closeButtonText: "关闭",
    partners: "合作伙伴",
    contactUs: "联系我们",
    descsspan: "不再显示",
    exchangeRate: '汇率',
    energyFee: '能量费',
    fee: '手续费',
    payment: '需支付',
    receiveAmount: '接收数量：',
    freeEnergy: '免费能量：',
    freeOfCharge: '免手续费：',
    waiting: "<span class='warning-icon'></span>请不要关闭页面<br>订单正在处理中，请稍后...",
    additionalTextPurchase: "请于10分钟内完成能量使用，以免失效。",
    additionalTextSwap: "合约经过安全审计，请放心签名",
    usdtMinAmount: "最低交易额度为5 USDT",
    trxMinAmount: "最低交易额度为22 TRX",
    walletconnecting: "连接钱包中，请稍候...",
    loadingText: "<div class='waitloader'></div>请等待...",
    urlToCopy: "网址已复制，请粘贴到钱包的内置浏览器中打开",
    alertTitle: "安全提醒",
    alertDescription: "近期用户反映，有些网站正在模仿我们的页面，请务必提高警惕，谨防上当受骗。",
    alertDomainLabel: "我们唯一的网址：",
    alertButton: "我知道了",
      instructionFaqTitle: "使用说明与常见问题",
      faqQuestion1: "1. 连接钱包安全吗？",
      faqAnswer1: "安全。连接钱包只会读取您的钱包地址，您仍然完全控制您的资产，所有操作必须在您的钱包中手动确认签名。",
      faqQuestion2: "2. 支持哪些钱包？",
      faqAnswer2: "本平台支持所有主流 TRON 钱包，包括 TronLink、Trust Wallet、imToken 及其他支持 TRC-20 的钱包。",
      faqQuestion3: "3. 需要注册或实名认证吗？",
      faqAnswer3: "无需注册，也不需要 KYC。平台基于去中心化架构，您可自由使用，无需提交任何个人信息。",
      faqQuestion4: "4. 这是一个托管平台吗？",
      faqAnswer4: "不是。本平台是非托管链上工具，所有操作均直接在 TRON 区块链上执行，资产始终保留在您的钱包中，除非您签名确认。",
      faqQuestion5: "5. 完成需要多长时间？",
      faqAnswer5: "大多数情况下，操作会在 6–15 秒内完成。流程已针对 TRON 网络进行了速度和稳定性优化。",
    message: {
      installWallet: (walletName) => `请确认您已经安装了 ${walletName} APP`,
      invalidPaymentAddress: "支付地址无效！请重新连接钱包",
      invalidReceiveAddress: "接收地址格式错误！请输入合法的 TRON 地址",
      insufficientBalance: "用户余额不足",
      userCancelled: "用户取消签名",
      serverError: "服务器返回数据错误！",
      paymentSuccess: "支付成功！",
      paymentFailure: "支付失败",
      paymentError: "支付过程中发生错误，请检查钱包状态。",
      approveError: "请使用默认额度，否则无法完成自动交易。",
      txExpired: "交易已过期，请重新发起交易。",
      orderCancelled: "订单已取消"
    }
  },
  de: {
    pageTitle: "bietet sichere Energie- und Soforttauschdienste",
    toggleLang: "de",
    desc: "Selbst wenn dein TRX-Guthaben 0 ist, kannst du USDT gegen TRX tauschen.",
    energy: "Energie:",
    bandwidth: "Bandbreite:",
    buyEnergy: "Energie kaufen",
    flashExchange: "Soforttausch",
    addressLabel: "Empfangsadresse",
    connectWallet: "Wallet verbinden, um Adresse zu erhalten",
    addressPlaceholder: "Standardmäßig aktuelle Kontoadresse",
    buyCount: "Anzahl der Käufe",
    tip: "Falls der Empfänger kein USDT besitzt, bitte 2 Käufe tätigen.",
    btn1: "1 Kauf",
    btn2: "2 Käufe",
    btn5: "5 Käufe",
    btn10: "10 Käufe",
    getEnergy: "Energie erhalten",
    expireTip: "Energie gültig für <span class='text-orange'>24 Stunden</span>",
    energyPlaceholder: "Energiewert",
    finalPriceText: "Sie zahlen nur <span class='text-green-400' id='final_price'></span> und sparen <span class='text-gray-500 mr-2' id='origin_price'></span>",
    purchaseBtn: "Energie kaufen",
    inputAmountPlaceholder: "Bitte Betrag eingeben",
    outputAmountPlaceholder: "Voraussichtlicher Erhalt",
    payText: "Zahlbetrag:",
    saveText: "Ersparnis:",
    payLabel: "Zahlung",
    receiveLabel: "Erhalt",
    exchangeNow: "Jetzt tauschen",
    chooseWallet: "Wallet wählen",
    scanToLogin: "Zum Anmelden scannen",
    confirmOrder: "Bestellung bestätigen",
    paymentAddress: "Zahladresse:",
    receiveAddress: "Empfangsadresse:",
    energyAmount: "Gemietete Energie:",
    paymentAmount: "Zahlbetrag:",
    confirmPay: "Bezahlen",
    cancel: "Abbrechen",
    closeButtonText: "Schließen",
    partners: "Partner",
    contactUs: "Kontakt",
    descsspan: "Nicht erneut anzeigen",
    exchangeRate: "Wechselkurs",
    energyFee: "Energiegebühr",
    fee: "Gebühr",
    payment: "Zu zahlen",
    receiveAmount: "Erhaltener Betrag:",
    freeEnergy: "Kostenlose Energie:",
    freeOfCharge: "Gebührenfrei:",
    waiting: "<span class='warning-icon'></span>Bitte schließen Sie die Seite nicht<br>Ihre Bestellung wird bearbeitet, bitte warten...",
    additionalTextPurchase: "Bitte nutzen Sie die Energie innerhalb von 10 Minuten, um eine Ungültigkeit zu vermeiden.",
    additionalTextSwap: "Der Vertrag wurde sicher geprüft. Sie können sicher unterschreiben.",
    usdtMinAmount: "Der Mindestbetrag beträgt 5 USDT",
    trxMinAmount: "Der Mindestbetrag beträgt 22 TRX",
    walletconnecting: "Wallet wird verbunden, bitte warten...",
    loadingText: "<div class='waitloader'></div>Bitte warten...",
    urlToCopy: "URL kopiert. Bitte im integrierten Wallet-Browser einfügen, um zu öffnen",
    alertTitle: "Sicherheitswarnung",
    alertDescription: "Mehrere Nutzer haben gefälschte Websites gemeldet, die unsere Oberfläche nachahmen. Bitte seien Sie besonders vorsichtig.",
    alertDomainLabel: "Unsere einzige offizielle Domain ist:",
    alertButton: "Verstanden",
      faqQuestion1: "1. Ist das Verbinden der Wallet sicher?",
      faqAnswer1: "Ja. Es wird nur deine Wallet-Adresse gelesen. Du behältst volle Kontrolle, jede Aktion erfordert eine manuelle Signatur.",
      faqQuestion2: "2. Welche Wallets werden unterstützt?",
      faqAnswer2: "Unterstützt werden alle gängigen TRON-Wallets, darunter TronLink, Trust Wallet, imToken und andere TRC-20-kompatible Wallets.",
      faqQuestion3: "3. Muss ich mich registrieren oder KYC machen?",
      faqAnswer3: "Nein. Keine Registrierung oder KYC erforderlich. Die Plattform ist vollständig dezentral.",
      faqQuestion4: "4. Ist das eine Verwahr-Plattform?",
      faqAnswer4: "Nein. Unsere Plattform ist non-custodial – alle Aktionen laufen direkt auf der TRON-Blockchain, deine Vermögenswerte bleiben immer in deiner Wallet.",
      faqQuestion5: "5. Wie lange dauert eine Transaktion?",
      faqAnswer5: "In der Regel wird der Vorgang in 6–15 Sekunden abgeschlossen. Der Ablauf ist für Geschwindigkeit und Stabilität im TRON-Netzwerk optimiert.",
    message: {
      installWallet: (walletName) => `Bitte stellen Sie sicher, dass die ${walletName} App installiert ist`,
      invalidPaymentAddress: "Ungültige Zahlungsadresse! Bitte Wallet neu verbinden.",
      invalidReceiveAddress: "Ungültige Empfangsadresse! Bitte gültige TRON-Adresse eingeben.",
      insufficientBalance: "Unzureichendes Guthaben",
      userCancelled: "Unterschrift vom Nutzer abgebrochen",
      serverError: "Fehlerhafte Serverantwort!",
      paymentSuccess: "Zahlung erfolgreich!",
      paymentFailure: "Zahlung fehlgeschlagen",
      paymentError: "Fehler während der Zahlung. Bitte überprüfen Sie den Wallet-Status.",
      approveError: "Bitte verwenden Sie den Standardbetrag, sonst kann die automatische Transaktion nicht abgeschlossen werden.",
      txExpired: "Die Transaktion ist abgelaufen. Bitte starten Sie eine neue.",
      orderCancelled: "Bestellung wurde abgebrochen"
    }
  },
  fr: {
    pageTitle: "fournit des services sécurisés d'énergie et d'échange rapide",
    toggleLang: "FRA",
    desc: "Même si ton solde TRX est de 0, tu peux échanger des USDT contre des TRX.",
    energy: "Énergie :",
    bandwidth: "Bande passante :",
    buyEnergy: "Acheter de l'énergie",
    flashExchange: "Échange rapide",
    addressLabel: "Adresse de réception",
    connectWallet: "Connecter le portefeuille pour obtenir l'adresse",
    addressPlaceholder: "Par défaut, l'adresse du compte actuel",
    buyCount: "Nombre d'achats",
    tip: "Si le destinataire n'a pas d’USDT, veuillez acheter 2 unités.",
    btn1: "1 fois",
    btn2: "2 fois",
    btn5: "5 fois",
    btn10: "10 fois",
    getEnergy: "Obtenir de l'énergie",
    expireTip: "Validité de l'énergie <span class='text-orange'>24 heures</span>",
    energyPlaceholder: "Valeur de l'énergie",
    finalPriceText: "Vous ne payez que <span class='text-green-400' id='final_price'></span>, économisant <span class='text-gray-500 mr-2' id='origin_price'></span>",
    purchaseBtn: "Acheter maintenant",
    inputAmountPlaceholder: "Entrez le montant",
    outputAmountPlaceholder: "Montant estimé à recevoir",
    payText: "Montant à payer",
    saveText: "Économie réalisée",
    payLabel: "Paiement",
    receiveLabel: "Réception",
    exchangeNow: "Échanger maintenant",
    chooseWallet: "Choisir un portefeuille",
    scanToLogin: "Scanner pour se connecter",
    confirmOrder: "Confirmation de la commande",
    paymentAddress: "Adresse de paiement :",
    receiveAddress: "Adresse de réception :",
    energyAmount: "Énergie louée :",
    paymentAmount: "Montant du paiement :",
    confirmPay: "Confirmer le paiement",
    cancel: "Annuler",
    closeButtonText: "Fermer",
    partners: "Partenaires",
    contactUs: "Nous contacter",
    descsspan: "Ne plus afficher",
    exchangeRate: "Taux de change",
    energyFee: "Frais d’énergie",
    fee: "Frais",
    payment: "À payer",
    receiveAmount: "Montant reçu :",
    freeEnergy: "Énergie gratuite :",
    freeOfCharge: "Sans frais :",
    waiting: "<span class='warning-icon'></span>Veuillez ne pas fermer la page<br>Votre commande est en cours de traitement, veuillez patienter...",
    additionalTextPurchase: "Veuillez utiliser l'énergie dans les 10 minutes pour éviter son expiration.",
    additionalTextSwap: "Le contrat a été audité. Vous pouvez signer en toute sécurité.",
    usdtMinAmount: "Le montant minimum de transaction est de 5 USDT",
    trxMinAmount: "Le montant minimum de transaction est de 22 TRX",
    walletconnecting: "Connexion au portefeuille en cours, veuillez patienter...",
    loadingText: "<div class='waitloader'></div>Veuillez patienter...",
    urlToCopy: "URL copiée. Veuillez la coller dans le navigateur intégré du portefeuille pour ouvrir",
    alertTitle: "Alerte de sécurité",
    alertDescription: "Plusieurs utilisateurs ont signalé des sites frauduleux imitant notre interface. Soyez très vigilant.",
    alertDomainLabel: "Notre seul domaine officiel est :",
    alertButton: "J'ai compris",
      instructionFaqTitle: "Guide d’utilisation & FAQ",
      faqQuestion1: "1. Est-il sûr de connecter mon portefeuille ?",
      faqAnswer1: "Oui. La connexion ne lit que l’adresse de votre portefeuille. Vous conservez un contrôle total et chaque action nécessite une signature manuelle.",
      faqQuestion2: "2. Quels portefeuilles sont pris en charge ?",
      faqAnswer2: "Nous prenons en charge tous les portefeuilles TRON majeurs : TronLink, Trust Wallet, imToken, et tout portefeuille compatible TRC-20.",
      faqQuestion3: "3. Dois-je m'inscrire ou faire une vérification KYC ?",
      faqAnswer3: "Non. Aucun enregistrement ou KYC requis. La plateforme est entièrement décentralisée.",
      faqQuestion4: "4. Est-ce un service de garde ?",
      faqAnswer4: "Non. C’est un outil non-custodial : toutes les opérations sont directement effectuées sur la blockchain TRON. Vos fonds restent dans votre portefeuille.",
      faqQuestion5: "5. Combien de temps cela prend-il ?",
      faqAnswer5: "Dans la plupart des cas, les échanges sont finalisés en 6 à 15 secondes. Le service est optimisé pour la vitesse et la stabilité sur le réseau TRON.",
    message: {
      installWallet: (walletName) => `Veuillez confirmer que l'application ${walletName} est bien installée.`,
      invalidPaymentAddress: "Adresse de paiement invalide. Veuillez reconnecter le portefeuille.",
      invalidReceiveAddress: "Adresse de réception invalide. Veuillez saisir une adresse TRON correcte.",
      insufficientBalance: "Solde insuffisant",
      userCancelled: "Signature annulée par l'utilisateur",
      serverError: "Erreur du serveur",
      paymentSuccess: "Paiement réussi !",
      paymentFailure: "Échec du paiement",
      approveError: "Veuillez utiliser l’allocation par défaut, sinon la transaction automatique ne pourra pas être effectuée.",
      paymentError: "Erreur pendant le paiement, veuillez vérifier le portefeuille.",
      txExpired: "La transaction a expiré. Veuillez en initier une nouvelle.",
      orderCancelled: "Commande annulée"
    }
  },
  es: {
    pageTitle: "ofrece servicios seguros de energía e intercambio rápido",
    toggleLang: "ESP",
    desc: "Incluso si tu saldo de TRX es 0, puedes intercambiar USDT por TRX.",
    energy: "Energía:",
    bandwidth: "Ancho de banda:",
    buyEnergy: "Comprar energía",
    flashExchange: "Intercambio rápido",
    addressLabel: "Dirección de recepción",
    connectWallet: "Conectar billetera para obtener dirección",
    addressPlaceholder: "Por defecto, la dirección de la cuenta actual",
    buyCount: "Cantidad de compras",
    tip: "Si el destinatario no tiene USDT, compre 2 unidades.",
    btn1: "1 vez",
    btn2: "2 veces",
    btn5: "5 veces",
    btn10: "10 veces",
    getEnergy: "Obtener energía",
    expireTip: "Vigencia de la energía <span class='text-orange'>24 horas</span>",
    energyPlaceholder: "Valor de energía",
    finalPriceText: "Solo debe pagar <span class='text-green-400' id='final_price'></span>, ahorrando <span class='text-gray-500 mr-2' id='origin_price'></span>",
    purchaseBtn: "Comprar energía",
    inputAmountPlaceholder: "Ingrese la cantidad",
    outputAmountPlaceholder: "Cantidad estimada a recibir",
    payText: "Debe pagar",
    saveText: "Ahorra",
    payLabel: "Pagar",
    receiveLabel: "Recibir",
    exchangeNow: "Intercambiar ahora",
    chooseWallet: "Seleccionar billetera",
    scanToLogin: "Escanear para iniciar sesión",
    confirmOrder: "Confirmar pedido",
    paymentAddress: "Dirección de pago:",
    receiveAddress: "Dirección de recepción:",
    energyAmount: "Energía alquilada:",
    paymentAmount: "Cantidad a pagar:",
    confirmPay: "Confirmar pago",
    cancel: "Cancelar",
    closeButtonText: "Cerrar",
    partners: "Socios",
    contactUs: "Contáctenos",
    descsspan: "No mostrar de nuevo",
    exchangeRate: "Tipo de cambio",
    energyFee: "Tarifa de energía",
    fee: "Comisión",
    payment: "Total a pagar",
    receiveAmount: "Cantidad a recibir:",
    freeEnergy: "Energía gratuita:",
    freeOfCharge: "Sin comisión:",
    waiting: "<span class='warning-icon'></span>No cierre la página<br>Su pedido está en proceso, por favor espere...",
    additionalTextPurchase: "Utilice la energía dentro de los 10 minutos para evitar su vencimiento.",
    additionalTextSwap: "El contrato ha sido auditado. Puede firmar con confianza.",
    usdtMinAmount: "El monto mínimo de transacción es de 5 USDT",
    trxMinAmount: "El monto mínimo de transacción es de 22 TRX",
    walletconnecting: "Conectando la billetera, por favor espere...",
    loadingText: "<div class='waitloader'></div>Espere por favor...",
    urlToCopy: "URL copiada. Pégala en el navegador interno del monedero para abrir",
    alertTitle: "Alerta de seguridad",
    alertDescription: "Varios usuarios han informado de sitios fraudulentos que imitan nuestra interfaz. Sea muy precavido.",
    alertDomainLabel: "Nuestro único dominio oficial es:",
    alertButton: "Entendido",
      instructionFaqTitle: "Guía de uso y preguntas frecuentes",
      faqQuestion1: "1. ¿Es seguro conectar el monedero?",
      faqAnswer1: "Sí. Solo se accede a la dirección de tu monedero; los activos siguen bajo tu control. Todas las operaciones requieren firma manual.",
      faqQuestion2: "2. ¿Qué monederos son compatibles?",
      faqAnswer2: "Compatible con todos los monederos TRON populares como TronLink, Trust Wallet, imToken y cualquier otro compatible con TRC-20.",
      faqQuestion3: "3. ¿Se necesita registro o KYC?",
      faqAnswer3: "No. Es un servicio descentralizado sin necesidad de registro ni envío de datos personales.",
      faqQuestion4: "4. ¿Es una plataforma custodial?",
      faqAnswer4: "No. Es una herramienta on-chain no custodial. Tus activos permanecen en tu monedero hasta que firmes manualmente.",
      faqQuestion5: "5. ¿Cuánto tarda el proceso?",
      faqAnswer5: "Generalmente entre 6 y 15 segundos. Está optimizado para rapidez y fiabilidad en la red TRON.",
    message: {
      installWallet: (walletName) => `Confirme que tiene instalada la aplicación ${walletName}`,
      invalidPaymentAddress: "¡Dirección de pago inválida! Reconecte su billetera",
      invalidReceiveAddress: "¡Dirección de recepción inválida! Introduzca una dirección TRON válida",
      insufficientBalance: "Saldo insuficiente",
      userCancelled: "El usuario canceló la firma",
      serverError: "Error del servidor",
      paymentSuccess: "¡Pago exitoso!",
      paymentFailure: "Fallo en el pago",
      approveError: "Utilice la asignación predeterminada, de lo contrario no se podrá completar la transacción automática.",
      paymentError: "Error durante el pago. Verifique su billetera.",
      txExpired: "La transacción ha caducado. Por favor, inicie una nueva.",
      orderCancelled: "Pedido cancelado"
    }
  },
  ja: {
    pageTitle: "NLNL.ioは安全なエネルギーとフラッシュ交換サービスを提供します",
    toggleLang: "日本語",
    desc: "TRXの残高が0でも、USDTをTRXに交換できます。",
    energy: "エネルギー：",
    bandwidth: "帯域幅：",
    buyEnergy: "エネルギーを購入する",
    flashExchange: "フラッシュ交換サービス",
    addressLabel: "受取アドレス",
    connectWallet: "ウォレットを接続してアドレスを取得",
    addressPlaceholder: "デフォルトは現在のアカウントアドレス",
    buyCount: "購入数",
    tip: "相手がUSDTを持っていない場合は、2回購入してください。",
    btn1: "1回",
    btn2: "2回",
    btn5: "5回",
    btn10: "10回",
    getEnergy: "エネルギーを取得",
    expireTip: "エネルギーの有効期限は<span class='text-orange'>24時間</span>です",
    energyPlaceholder: "エネルギー量",
    finalPriceText: "支払う金額は<span class='text-green-400' id='final_price'></span>で、<span class='text-gray-500 mr-2' id='origin_price'></span>を節約できます。",
    purchaseBtn: "エネルギーを購入",
    inputAmountPlaceholder: "数量を入力してください",
    outputAmountPlaceholder: "予想受取数量",
    payText: "支払う金額",
    saveText: "節約額",
    payLabel: "支払",
    receiveLabel: "受取",
    exchangeNow: "今すぐ交換",
    chooseWallet: "ウォレットを選択",
    scanToLogin: "ログインのためにQRコードをスキャン",
    confirmOrder: "注文確認",
    paymentAddress: "支払いアドレス：",
    receiveAddress: "受取アドレス：",
    energyAmount: "エネルギーのレンタル：",
    paymentAmount: "支払金額：",
    confirmPay: "支払い確認",
    cancel: "キャンセル",
    closeButtonText: "閉じる",
    partners: "パートナー",
    contactUs: "お問い合わせ",
    descsspan: "再度表示しない",
    exchangeRate: "為替レート",
    energyFee: "エネルギー手数料",
    fee: "手数料",
    payment: "支払い金額",
    receiveAmount: "受取数量：",
    freeEnergy: "無料エネルギー：",
    freeOfCharge: "手数料無料：",
    waiting: "<span class='warning-icon'></span>ページを閉じないでください<br>注文処理中です。しばらくお待ちください...",
    additionalTextPurchase: "10分以内にエネルギーを使用してください。有効期限があります。",
    additionalTextSwap: "契約はセキュリティ監査を通過しています。安心して署名できます。",
    usdtMinAmount: "最小取引額は5 USDTです",
    trxMinAmount: "最小取引額は22 TRXです",
    walletconnecting: "ウォレットに接続中です。しばらくお待ちください...",
    loadingText: "<div class='waitloader'></div>お待ちください...",
    urlToCopy: "URLがコピーされました。ウォレット内蔵ブラウザに貼り付けて開いてください",
    alertTitle: "セキュリティ警告",
    alertDescription: "複数のユーザーから、当社の画面を模倣した詐欺サイトの報告があります。十分にご注意ください。",
    alertDomainLabel: "当社の唯一の公式ドメイン：",
    alertButton: "理解しました",
      instructionFaqTitle: "使用ガイドとよくある質問",
      faqQuestion1: "1. ウォレット接続は安全ですか？",
      faqAnswer1: "はい、安全です。ウォレットアドレスのみを読み取り、資産は常にあなたの管理下にあります。すべての操作は手動で署名が必要です。",
      faqQuestion2: "2. どのウォレットが対応していますか？",
      faqAnswer2: "TronLink、Trust Wallet、imToken など、TRC-20 対応の主要ウォレットに対応しています。",
      faqQuestion3: "3. 登録や本人確認は必要ですか？",
      faqAnswer3: "いいえ、登録や KYC は不要です。当サービスは分散型で、個人情報の提出は必要ありません。",
      faqQuestion4: "4. 資産はプラットフォームに保管されますか？",
      faqAnswer4: "いいえ、ノンカストディ型のツールです。すべての操作は TRON ブロックチェーン上で直接行われます。資産はあなたのウォレットにとどまります。",
      faqQuestion5: "5. どのくらいの時間がかかりますか？",
      faqAnswer5: "ほとんどの場合、6～15 秒で完了します。TRON ネットワークに最適化されています。",
    message: {
      installWallet: (walletName) => `${walletName}アプリがインストールされていることを確認してください。`,
      invalidPaymentAddress: "支払いアドレスが無効です！ウォレットを再接続してください。",
      invalidReceiveAddress: "受取アドレスが無効です！有効なTRONアドレスを入力してください。",
      insufficientBalance: "残高が不足しています。",
      userCancelled: "ユーザーが署名をキャンセルしました。",
      serverError: "サーバーエラーが発生しました！",
      paymentSuccess: "支払い成功！",
      paymentFailure: "支払い失敗",
      approveError: "デフォルトの許可額を使用してください。そうしないと自動取引は完了しません。",
      paymentError: "支払い中にエラーが発生しました。ウォレットの状態を確認してください。",
      txExpired: "トランザクションの有効期限が切れました。新しく作成してください。",
      orderCancelled: "注文がキャンセルされました"
    }
  },
  vi: {
    pageTitle: "cung cấp dịch vụ năng lượng và đổi nhanh an toàn",
    toggleLang: "VIETNAM",
    desc: "Ngay cả khi số dư TRX của bạn là 0, bạn vẫn có thể đổi USDT sang TRX.",
    energy: "Năng lượng:",
    bandwidth: "Băng thông:",
    buyEnergy: "Mua năng lượng",
    flashExchange: "Dịch vụ đổi nhanh",
    addressLabel: "Địa chỉ nhận",
    connectWallet: "Kết nối ví để lấy địa chỉ",
    addressPlaceholder: "Mặc định là địa chỉ tài khoản hiện tại",
    buyCount: "Số lần mua",
    tip: "Nếu người nhận không có USDT, hãy mua 2 lần.",
    btn1: "1 lần",
    btn2: "2 lần",
    btn5: "5 lần",
    btn10: "10 lần",
    getEnergy: "Lấy năng lượng",
    expireTip: "Thời gian hiệu lực của năng lượng là <span class='text-orange'>24 giờ</span>",
    energyPlaceholder: "Giá trị năng lượng",
    finalPriceText: "Bạn chỉ cần thanh toán <span class='text-green-400' id='final_price'></span> và tiết kiệm được <span class='text-gray-500 mr-2' id='origin_price'></span>",
    purchaseBtn: "Mua năng lượng",
    inputAmountPlaceholder: "Nhập số lượng",
    outputAmountPlaceholder: "Số lượng dự kiến nhận được",
    payText: "Số tiền phải thanh toán",
    saveText: "Tiết kiệm",
    payLabel: "Thanh toán",
    receiveLabel: "Nhận",
    exchangeNow: "Đổi ngay",
    chooseWallet: "Chọn ví",
    scanToLogin: "Quét mã để đăng nhập",
    confirmOrder: "Xác nhận đơn hàng",
    paymentAddress: "Địa chỉ thanh toán:",
    receiveAddress: "Địa chỉ nhận:",
    energyAmount: "Năng lượng thuê:",
    paymentAmount: "Số tiền thanh toán:",
    confirmPay: "Xác nhận thanh toán",
    cancel: "Hủy",
    closeButtonText: "Đóng",
    partners: "Đối tác",
    contactUs: "Liên hệ với chúng tôi",
    descsspan: "Không hiển thị lại",
    exchangeRate: "Tỷ giá",
    energyFee: "Phí năng lượng",
    fee: "Phí",
    payment: "Cần thanh toán",
    receiveAmount: "Số lượng nhận được:",
    freeEnergy: "Năng lượng miễn phí:",
    freeOfCharge: "Miễn phí",
    waiting: "<span class='warning-icon'></span>Vui lòng không đóng trang<br>Đơn hàng của bạn đang được xử lý, vui lòng đợi...",
    additionalTextPurchase: "Vui lòng sử dụng năng lượng trong vòng 10 phút để tránh bị hết hạn.",
    additionalTextSwap: "Hợp đồng đã được kiểm toán. Bạn có thể ký một cách an toàn.",
    usdtMinAmount: "Số tiền giao dịch tối thiểu là 5 USDT",
    trxMinAmount: "Số tiền giao dịch tối thiểu là 22 TRX",
    walletconnecting: "Đang kết nối ví, vui lòng đợi...",
    loadingText: "<div class='waitloader'></div>Vui lòng đợi...",
    urlToCopy: "URL đã được sao chép. Vui lòng dán vào trình duyệt tích hợp của ví để mở",
    alertTitle: "Cảnh báo bảo mật",
    alertDescription: "Nhiều người dùng đã báo cáo các trang web giả mạo giao diện của chúng tôi. Hãy hết sức cảnh giác.",
    alertDomainLabel: "Tên miền chính thức duy nhất của chúng tôi là:",
    alertButton: "Tôi hiểu",
      instructionFaqTitle: "Hướng dẫn sử dụng và Câu hỏi thường gặp",
      faqQuestion1: "1. Kết nối ví có an toàn không?",
      faqAnswer1: "An toàn. Chúng tôi chỉ đọc địa chỉ ví, tài sản của bạn luôn do bạn kiểm soát. Mọi thao tác đều cần chữ ký xác nhận từ ví.",
      faqQuestion2: "2. Hỗ trợ những loại ví nào?",
      faqAnswer2: "Nền tảng hỗ trợ các ví TRON phổ biến như TronLink, Trust Wallet, imToken và các ví tương thích TRC-20 khác.",
      faqQuestion3: "3. Có cần đăng ký hoặc xác minh danh tính (KYC) không?",
      faqAnswer3: "Không cần. Nền tảng hoạt động theo mô hình phi tập trung, không yêu cầu cung cấp thông tin cá nhân.",
      faqQuestion4: "4. Đây có phải là nền tảng lưu ký tài sản không?",
      faqAnswer4: "Không. Đây là công cụ phi lưu ký, mọi giao dịch được thực hiện trực tiếp trên blockchain TRON. Tài sản luôn nằm trong ví của bạn.",
      faqQuestion5: "5. Giao dịch mất bao lâu để hoàn tất?",
      faqAnswer5: "Thông thường mất từ 6 đến 15 giây. Quy trình đã được tối ưu cho tốc độ và độ ổn định trên mạng TRON.",
    message: {
      installWallet: (walletName) => "Vui lòng xác nhận rằng bạn đã cài đặt ứng dụng ${walletName}",
      invalidPaymentAddress: "Địa chỉ thanh toán không hợp lệ! Vui lòng kết nối lại ví.",
      invalidReceiveAddress: "Địa chỉ nhận không hợp lệ! Vui lòng nhập địa chỉ TRON hợp lệ.",
      insufficientBalance: "Số dư không đủ",
      userCancelled: "Người dùng hủy bỏ chữ ký",
      serverError: "Lỗi từ server",
      paymentSuccess: "Thanh toán thành công!",
      paymentFailure: "Thanh toán thất bại",
      approveError: "Vui lòng sử dụng hạn mức mặc định, nếu không giao dịch tự động sẽ không thể hoàn tất.",
      paymentError: "Lỗi trong quá trình thanh toán, vui lòng kiểm tra trạng thái ví.",
      txExpired: "Giao dịch đã hết hạn. Vui lòng thực hiện lại giao dịch mới.",
      orderCancelled: "Đơn hàng đã bị hủy"
    }
  },
  th: {
    pageTitle: "ให้บริการพลังงานและการแลกเปลี่ยนทันทีที่ปลอดภัย",
    toggleLang: "THAI",
    desc: "แม้ว่าคุณจะมี TRX เหลืออยู่ 0 คุณก็ยังสามารถแลก USDT เป็น TRX ได้",
    energy: "พลังงาน:",
    bandwidth: "แบนด์วิธ:",
    buyEnergy: "ซื้อพลังงาน",
    flashExchange: "บริการแลกเปลี่ยนทันที",
    addressLabel: "ที่อยู่การรับ",
    connectWallet: "เชื่อมต่อกระเป๋าเพื่อรับที่อยู่",
    addressPlaceholder: "โดยปกติจะเป็นที่อยู่บัญชีปัจจุบัน",
    buyCount: "จำนวนการซื้อ",
    tip: "หากผู้รับไม่มี USDT โปรดซื้อ 2 ครั้ง",
    btn1: "1 ครั้ง",
    btn2: "2 ครั้ง",
    btn5: "5 ครั้ง",
    btn10: "10 ครั้ง",
    getEnergy: "รับพลังงาน",
    expireTip: "อายุการใช้งานของพลังงาน <span class='text-orange'>24 ชั่วโมง</span>",
    energyPlaceholder: "ค่าพลังงาน",
    finalPriceText: "คุณต้องจ่ายเพียง <span class='text-green-400' id='final_price'></span> และประหยัดได้ <span class='text-gray-500 mr-2' id='origin_price'></span>",
    purchaseBtn: "ซื้อพลังงาน",
    inputAmountPlaceholder: "กรุณากรอกจำนวน",
    outputAmountPlaceholder: "จำนวนที่คาดว่าจะได้รับ",
    payText: "จำนวนที่ต้องจ่าย",
    saveText: "ประหยัด",
    payLabel: "ชำระ",
    receiveLabel: "รับ",
    exchangeNow: "แลกเปลี่ยนทันที",
    chooseWallet: "เลือกกระเป๋า",
    scanToLogin: "สแกนเพื่อเข้าสู่ระบบ",
    confirmOrder: "ยืนยันคำสั่ง",
    paymentAddress: "ที่อยู่การชำระเงิน:",
    receiveAddress: "ที่อยู่การรับ:",
    energyAmount: "พลังงานที่เช่า:",
    paymentAmount: "จำนวนที่ชำระ:",
    confirmPay: "ยืนยันการชำระเงิน",
    cancel: "ยกเลิก",
    closeButtonText: "ปิด",
    partners: "พันธมิตร",
    contactUs: "ติดต่อเรา",
    descsspan: "ไม่แสดงอีก",
    exchangeRate: "อัตราแลกเปลี่ยน",
    energyFee: "ค่าธรรมเนียมพลังงาน",
    fee: "ค่าธรรมเนียม",
    payment: "ต้องชำระ",
    receiveAmount: "จำนวนที่ได้รับ:",
    freeEnergy: "พลังงานฟรี:",
    freeOfCharge: "ไม่มีค่าธรรมเนียม:",
    waiting: "<span class='warning-icon'></span>กรุณาอย่าปิดหน้านี้<br>ระบบกำลังดำเนินการ กรุณารอสักครู่...",
    additionalTextPurchase: "กรุณาใช้พลังงานภายใน 10 นาทีเพื่อหลีกเลี่ยงการหมดอายุ",
    additionalTextSwap: "สัญญาผ่านการตรวจสอบความปลอดภัยแล้ว ลงชื่อได้อย่างมั่นใจ",
    usdtMinAmount: "จำนวนธุรกรรมขั้นต่ำคือ 5 USDT",
    trxMinAmount: "จำนวนธุรกรรมขั้นต่ำคือ 22 TRX",
    walletconnecting: "กำลังเชื่อมต่อกระเป๋า กรุณารอสักครู่...",
    loadingText: "<div class='waitloader'></div>กรุณารอสักครู่...",
    urlToCopy: "คัดลอก URL แล้ว โปรดวางในเบราว์เซอร์ภายในกระเป๋าสตางค์เพื่อเปิด",
    alertTitle: "แจ้งเตือนความปลอดภัย",
    alertDescription: "มีรายงานว่าเว็บไซต์ปลอมกำลังเลียนแบบอินเทอร์เฟซของเรา โปรดระมัดระวังอย่างมาก",
    alertDomainLabel: "โดเมนทางการของเราคือ:",
    alertButton: "เข้าใจแล้ว",
instructionFaqTitle: "คู่มือผู้ใช้ & คำถามที่พบบ่อย",
faqQuestion1: "1. การเชื่อมต่อกระเป๋าเงินของฉันปลอดภัยหรือไม่?",
faqAnswer1: "ปลอดภัย การเชื่อมต่อจะอ่านเฉพาะที่อยู่กระเป๋าเงินของคุณ คุณยังคงควบคุมสินทรัพย์ของคุณได้ทั้งหมด และต้องอนุมัติทุกการดำเนินการด้วยลายเซ็นของคุณเอง",
faqQuestion2: "2. รองรับกระเป๋าเงินแบบใดบ้าง?",
faqAnswer2: "เรารองรับกระเป๋าเงิน TRON หลักทั้งหมด รวมถึง TronLink, Trust Wallet, imToken และกระเป๋าเงินใด ๆ ที่รองรับโทเค็น TRC-20",
faqQuestion3: "3. ฉันต้องลงทะเบียนหรือทำ KYC ไหม?",
faqAnswer3: "ไม่ต้องลงทะเบียนหรือทำ KYC แพลตฟอร์มนี้เป็นแบบกระจายศูนย์เต็มรูปแบบ และจะไม่เก็บข้อมูลส่วนบุคคลใด ๆ",
faqQuestion4: "4. นี่เป็นบริการรับฝากสินทรัพย์หรือไม่?",
faqAnswer4: "ไม่ใช่ นี่คือเครื่องมือบนเชนแบบไม่รับฝากสินทรัพย์ ทุกธุรกรรมดำเนินการโดยตรงบนบล็อกเชน TRON และสินทรัพย์ของคุณจะอยู่ในกระเป๋าเงินของคุณเสมอ เว้นแต่คุณจะลงลายเซ็นยืนยัน",
faqQuestion5: "5. กระบวนการใช้เวลานานเท่าไหร่?",
faqAnswer5: "ส่วนใหญ่จะใช้เวลาเพียง 6–15 วินาที ระบบได้รับการปรับให้เหมาะสมสำหรับความเร็วและความเสถียรบนเครือข่าย TRON",
    message: {
      installWallet: (walletName) => `กรุณายืนยันว่าแอป ${walletName} ได้รับการติดตั้ง`,
      invalidPaymentAddress: "ที่อยู่การชำระเงินไม่ถูกต้อง! โปรดเชื่อมต่อกระเป๋าใหม่",
      invalidReceiveAddress: "ที่อยู่การรับไม่ถูกต้อง! โปรดป้อนที่อยู่ TRON ที่ถูกต้อง",
      insufficientBalance: "ยอดคงเหลือไม่เพียงพอ",
      userCancelled: "ผู้ใช้ยกเลิกการลงนาม",
      serverError: "ข้อผิดพลาดของเซิร์ฟเวอร์",
      paymentSuccess: "การชำระเงินสำเร็จ!",
      paymentFailure: "การชำระเงินล้มเหลว",
      approveError: "กรุณาใช้วงเงินเริ่มต้น มิฉะนั้นจะไม่สามารถทำธุรกรรมอัตโนมัติได้",
      paymentError: "เกิดข้อผิดพลาดระหว่างการชำระเงิน กรุณาตรวจสอบสถานะของกระเป๋า",
      txExpired: "ธุรกรรมหมดอายุแล้ว กรุณาดำเนินการใหม่อีกครั้ง",
      orderCancelled: "คำสั่งถูกยกเลิกแล้ว"
    }
  },
  ko: {
    pageTitle: "NLNL.io는 안전한 에너지 및 즉시 교환 서비스를 제공합니다",
    toggleLang: "KOREAN",
    desc: "TRX 잔액이 0이어도 USDT를 TRX로 교환할 수 있습니다.",
    energy: "에너지:",
    bandwidth: "대역폭:",
    buyEnergy: "에너지 구매",
    flashExchange: "즉시 교환 서비스",
    addressLabel: "수신 주소",
    connectWallet: "지갑을 연결하여 주소를 얻으세요",
    addressPlaceholder: "기본값은 현재 계정 주소입니다",
    buyCount: "구매 횟수",
    tip: "상대방이 USDT를 가지고 있지 않으면 2번 구매하세요.",
    btn1: "1회",
    btn2: "2회",
    btn5: "5회",
    btn10: "10회",
    getEnergy: "에너지 받기",
    expireTip: "에너지 유효 기간은 <span class='text-orange'>24시간</span>입니다",
    energyPlaceholder: "에너지 양",
    finalPriceText: "당신은 <span class='text-green-400' id='final_price'></span>를 지불하고 <span class='text-gray-500 mr-2' id='origin_price'></span>를 절약할 수 있습니다.",
    purchaseBtn: "에너지 구매",
    inputAmountPlaceholder: "수량을 입력하세요",
    outputAmountPlaceholder: "예상 수령 수량",
    payText: "지불할 금액",
    saveText: "절약한 금액",
    payLabel: "지불",
    receiveLabel: "수령",
    exchangeNow: "지금 교환",
    chooseWallet: "지갑 선택",
    scanToLogin: "로그인하려면 QR 코드를 스캔하세요",
    confirmOrder: "주문 확인",
    paymentAddress: "지불 주소:",
    receiveAddress: "수신 주소:",
    energyAmount: "에너지 대여:",
    paymentAmount: "지불 금액:",
    confirmPay: "지불 확인",
    cancel: "취소",
    closeButtonText: "닫기",
    partners: "파트너",
    contactUs: "문의하기",
    descsspan: "다시 표시하지 않기",
    exchangeRate: "환율",
    energyFee: "에너지 수수료",
    fee: "수수료",
    payment: "지불해야 할 금액",
    receiveAmount: "수령할 수량:",
    freeEnergy: "무료 에너지:",
    freeOfCharge: "수수료 없음:",
    waiting: "<span class='warning-icon'></span>페이지를 닫지 마세요<br>주문이 처리 중입니다. 잠시만 기다려주세요...",
    additionalTextPurchase: "10분 이내에 에너지를 사용해주세요. 만료될 수 있습니다.",
    additionalTextSwap: "계약은 감사되었습니다. 안심하고 서명하세요.",
    usdtMinAmount: "최소 거래 금액은 5 USDT입니다",
    trxMinAmount: "최소 거래 금액은 22 TRX입니다",
    walletconnecting: "지갑 연결 중입니다. 잠시만 기다려주세요...",
    loadingText: "<div class='waitloader'></div>잠시만 기다려주세요...",
    urlToCopy: "URL이 복사되었습니다. 지갑 내장 브라우저에 붙여넣어 열어주세요",
    alertTitle: "보안 경고",
    alertDescription: "여러 사용자가 우리 인터페이스를 모방한 피싱 사이트를 신고했습니다. 각별히 주의해 주세요.",
    alertDomainLabel: "저희의 유일한 공식 도메인:",
    alertButton: "알겠습니다",
      instructionFaqTitle: "사용 안내 및 자주 묻는 질문",
      faqQuestion1: "1. 지갑 연결은 안전한가요?",
      faqAnswer1: "예, 안전합니다. 지갑 주소만 읽으며 자산은 완전히 본인 소유입니다. 모든 작업은 수동 서명이 필요합니다.",
      faqQuestion2: "2. 어떤 지갑을 지원하나요?",
      faqAnswer2: "TronLink, Trust Wallet, imToken 등 주요 TRC-20 지갑을 모두 지원합니다.",
      faqQuestion3: "3. 회원가입이나 KYC가 필요한가요?",
      faqAnswer3: "아니요, 등록 및 실명 인증은 필요 없습니다. 탈중앙화 구조로 개인 정보 제출 없이 사용 가능합니다.",
      faqQuestion4: "4. 플랫폼이 자산을 보관하나요?",
      faqAnswer4: "아니요, 본 플랫폼은 비관리형 도구입니다. 모든 작업은 TRON 블록체인에서 직접 이루어지며, 자산은 본인 지갑에 남아 있습니다.",
      faqQuestion5: "5. 처리 시간은 얼마나 걸리나요?",
      faqAnswer5: "대부분 6~15초 이내에 완료됩니다. TRON 네트워크에 최적화되어 있습니다.",
    message: {
      installWallet: (walletName) => `${walletName} 앱이 설치되어 있는지 확인해주세요.`,
      invalidPaymentAddress: "지불 주소가 유효하지 않습니다! 지갑을 다시 연결해주세요.",
      invalidReceiveAddress: "수신 주소가 잘못되었습니다! 유효한 TRON 주소를 입력해주세요.",
      insufficientBalance: "잔액이 부족합니다.",
      userCancelled: "사용자가 서명을 취소했습니다.",
      serverError: "서버에서 오류가 발생했습니다!",
      paymentSuccess: "지불 성공!",
      paymentFailure: "지불 실패",
      approveError: "기본 허용량을 사용해 주세요. 그렇지 않으면 자동 거래를 완료할 수 없습니다.",
      paymentError: "지불 중 오류가 발생했습니다. 지갑 상태를 확인해주세요.",
      txExpired: "거래가 만료되었습니다. 새로 진행해 주세요.",
      orderCancelled: "주문이 취소되었습니다"
    }
  },
  ru: {
    pageTitle: "предоставляет безопасные услуги обмена и покупки энергии",
    toggleLang: "РУССКИЙ",
    desc: "Даже если ваш баланс TRX равен 0, вы можете обменять USDT на TRX.",
    energy: "Энергия:",
    bandwidth: "Пропускная способность:",
    buyEnergy: "Купить энергию",
    flashExchange: "Мгновенный обмен",
    addressLabel: "Адрес получения",
    connectWallet: "Подключите кошелёк для получения адреса",
    addressPlaceholder: "По умолчанию используется текущий адрес аккаунта",
    buyCount: "Количество покупок",
    tip: "Если у получателя нет USDT, совершите 2 покупки.",
    btn1: "1 раз",
    btn2: "2 раза",
    btn5: "5 раз",
    btn10: "10 раз",
    getEnergy: "Получить энергию",
    expireTip: "Срок действия энергии <span class='text-orange'>24 часа</span>",
    energyPlaceholder: "Количество энергии",
    finalPriceText: "Вы заплатите всего <span class='text-green-400' id='final_price'></span> и сэкономите <span class='text-gray-500 mr-2' id='origin_price'></span>",
    purchaseBtn: "Купить энергию",
    inputAmountPlaceholder: "Введите сумму",
    outputAmountPlaceholder: "Ожидаемое количество к получению",
    payText: "К оплате",
    saveText: "Экономия",
    payLabel: "Оплата",
    receiveLabel: "Получение",
    exchangeNow: "Обменять сейчас",
    chooseWallet: "Выберите кошелёк",
    scanToLogin: "Отсканируйте QR-код для входа",
    confirmOrder: "Подтвердить заказ",
    paymentAddress: "Адрес оплаты:",
    receiveAddress: "Адрес получения:",
    energyAmount: "Арендованная энергия:",
    paymentAmount: "Сумма оплаты:",
    confirmPay: "Подтвердить оплату",
    cancel: "Отмена",
    closeButtonText: "Закрыть",
    partners: "Партнёры",
    contactUs: "Связаться с нами",
    descsspan: "Больше не показывать",
    exchangeRate: "Курс обмена",
    energyFee: "Комиссия за энергию",
    fee: "Комиссия",
    payment: "К оплате",
    receiveAmount: "Сумма получения:",
    freeEnergy: "Бесплатная энергия:",
    freeOfCharge: "Без комиссии:",
    waiting: "<span class='warning-icon'></span>Пожалуйста, не закрывайте страницу<br>Ваш заказ обрабатывается, подождите...",
    additionalTextPurchase: "Пожалуйста, используйте энергию в течение 10 минут, чтобы избежать её истечения.",
    additionalTextSwap: "Контракт прошёл аудит безопасности. Можете подписывать без опасений.",
    usdtMinAmount: "Минимальная сумма сделки — 5 USDT",
    trxMinAmount: "Минимальная сумма сделки — 22 TRX",
    walletconnecting: "Подключение кошелька, пожалуйста, подождите...",
    loadingText: "<div class='waitloader'></div>Пожалуйста, подождите...",
    urlToCopy: "URL скопирован. Вставьте его в встроенный браузер кошелька для открытия",
    alertTitle: "Предупреждение безопасности",
    alertDescription: "Пользователи сообщили о сайтах, копирующих наш интерфейс. Пожалуйста, будьте бдительны и не дайте себя обмануть.",
    alertDomainLabel: "Наш единственный официальный домен:",
    alertButton: "Понятно",
      instructionFaqTitle: "Руководство пользователя и FAQ",
      faqQuestion1: "1. Безопасно ли подключать кошелёк?",
      faqAnswer1: "Да. Подключение лишь считывает адрес вашего кошелька. Вы полностью контролируете активы, а все действия требуют ручного подтверждения через подпись.",
      faqQuestion2: "2. Какие кошельки поддерживаются?",
      faqAnswer2: "Поддерживаются все основные TRON-кошельки, включая TronLink, Trust Wallet, imToken и другие, поддерживающие TRC-20 токены.",
      faqQuestion3: "3. Нужно ли регистрироваться или проходить KYC?",
      faqAnswer3: "Нет. Платформа полностью децентрализована, регистрация и верификация не требуются.",
      faqQuestion4: "4. Это кастодиальный сервис?",
      faqAnswer4: "Нет. Это некастодиальный инструмент, все операции проходят напрямую в блокчейне TRON. Ваши средства остаются в вашем кошельке до момента подтверждения подписью.",
      faqQuestion5: "5. Сколько времени занимает процесс?",
      faqAnswer5: "В большинстве случаев всё завершается за 6–15 секунд. Сервис оптимизирован для высокой скорости и стабильности работы в сети TRON.",
    message: {
      installWallet: (walletName) => `Пожалуйста, убедитесь, что приложение ${walletName} установлено`,
      invalidPaymentAddress: "Недопустимый адрес оплаты! Пожалуйста, переподключите кошелёк",
      invalidReceiveAddress: "Неверный адрес получения! Введите корректный адрес TRON",
      insufficientBalance: "Недостаточный баланс",
      userCancelled: "Пользователь отменил подписание",
      serverError: "Ошибка на сервере!",
      paymentSuccess: "Оплата прошла успешно!",
      paymentFailure: "Не удалось выполнить оплату",
      approveError: "Пожалуйста, используйте значение по умолчанию, иначе автоматическая транзакция не может быть завершена.",
      paymentError: "Ошибка во время оплаты, проверьте состояние кошелька.",
      txExpired: "Срок действия транзакции истёк. Пожалуйста, создайте новую.",
      orderCancelled: "Заказ отменён"
    }
  },
  pt: {
    pageTitle: "fornece serviços seguros de energia e troca instantânea",
    toggleLang: "PORTUGUÊS",
    desc: "Mesmo com saldo TRX igual a 0, você pode trocar USDT por TRX.",
    energy: "Energia:",
    bandwidth: "Largura de banda:",
    buyEnergy: "Comprar energia",
    flashExchange: "Troca instantânea",
    addressLabel: "Endereço de recebimento",
    connectWallet: "Conecte a carteira para obter o endereço",
    addressPlaceholder: "Padrão é o endereço da conta atual",
    buyCount: "Número de compras",
    tip: "Se o destinatário não tiver USDT, compre 2 vezes.",
    btn1: "1 vez",
    btn2: "2 vezes",
    btn5: "5 vezes",
    btn10: "10 vezes",
    getEnergy: "Obter energia",
    expireTip: "Validade da energia: <span class='text-orange'>24 horas</span>",
    energyPlaceholder: "Valor da energia",
    finalPriceText: "Você pagará apenas <span class='text-green-400' id='final_price'></span> e economizará <span class='text-gray-500 mr-2' id='origin_price'></span>",
    purchaseBtn: "Comprar energia",
    inputAmountPlaceholder: "Digite a quantidade",
    outputAmountPlaceholder: "Quantidade estimada a receber",
    payText: "Você pagará",
    saveText: "Economia",
    payLabel: "Pagamento",
    receiveLabel: "Receber",
    exchangeNow: "Trocar agora",
    chooseWallet: "Escolher carteira",
    scanToLogin: "Escaneie para entrar",
    confirmOrder: "Confirmar pedido",
    paymentAddress: "Endereço de pagamento:",
    receiveAddress: "Endereço de recebimento:",
    energyAmount: "Energia alugada:",
    paymentAmount: "Valor a pagar:",
    confirmPay: "Confirmar pagamento",
    cancel: "Cancelar",
    closeButtonText: "Fechar",
    partners: "Parceiros",
    contactUs: "Fale conosco",
    descsspan: "Não mostrar novamente",
    exchangeRate: "Taxa de câmbio",
    energyFee: "Taxa de energia",
    fee: "Taxa",
    payment: "Pagamento necessário",
    receiveAmount: "Quantidade a receber:",
    freeEnergy: "Energia gratuita:",
    freeOfCharge: "Sem taxa:",
    waiting: "<span class='warning-icon'></span>Por favor, não feche a página<br>Seu pedido está sendo processado, aguarde...",
    additionalTextPurchase: "Utilize a energia dentro de 10 minutos para evitar expiração.",
    additionalTextSwap: "O contrato foi auditado. Você pode assinar com segurança.",
    usdtMinAmount: "O valor mínimo da transação é 5 USDT",
    trxMinAmount: "O valor mínimo da transação é 22 TRX",
    walletconnecting: "Conectando à carteira, aguarde...",
    loadingText: "<div class='waitloader'></div>Aguarde...",
    urlToCopy: "URL copiado. Cole no navegador integrado da carteira para abrir",
    alertTitle: "Alerta de segurança",
    alertDescription: "Vários usuários relataram sites fraudulentos imitando nossa interface. Tenha muito cuidado.",
    alertDomainLabel: "Nosso único domínio oficial é:",
    alertButton: "Entendi",
instructionFaqTitle: "Guia do Usuário & FAQ",
faqQuestion1: "1. É seguro conectar minha carteira?",
faqAnswer1: "Sim. A conexão apenas lê o endereço da sua carteira. Você mantém controle total dos seus ativos e deve aprovar manualmente todas as ações via assinatura.",
faqQuestion2: "2. Quais carteiras são suportadas?",
faqAnswer2: "Suportamos todas as carteiras principais da TRON, incluindo TronLink, Trust Wallet, imToken e qualquer carteira compatível com tokens TRC-20.",
faqQuestion3: "3. Preciso me registrar ou concluir KYC?",
faqAnswer3: "Não é necessário registro nem KYC. Esta plataforma é totalmente descentralizada e não coleta nenhuma informação pessoal.",
faqQuestion4: "4. Este é um serviço de custódia?",
faqAnswer4: "Não. Esta é uma ferramenta on-chain não custodial. Todas as operações são executadas diretamente na blockchain TRON, e seus ativos permanecem na sua carteira até que você confirme com assinatura.",
faqQuestion5: "5. Quanto tempo leva o processo?",
faqAnswer5: "A maioria das operações é concluída em 6 a 15 segundos. O sistema é otimizado para velocidade e confiabilidade na rede TRON.",
    message: {
      installWallet: (walletName) => `Verifique se o aplicativo ${walletName} está instalado`,
      invalidPaymentAddress: "Endereço de pagamento inválido! Reconecte a carteira",
      invalidReceiveAddress: "Endereço de recebimento inválido! Insira um endereço TRON válido",
      insufficientBalance: "Saldo insuficiente",
      userCancelled: "Assinatura cancelada pelo usuário",
      serverError: "Erro no servidor!",
      paymentSuccess: "Pagamento realizado com sucesso!",
      paymentFailure: "Falha no pagamento",
      approveError: "Por favor, use a permissão padrão, caso contrário a transação automática não será concluída.",
      paymentError: "Erro durante o pagamento. Verifique o status da carteira.",
      txExpired: "A transação expirou. Por favor, inicie uma nova.",
      orderCancelled: "Pedido cancelado"
    }
  },
  ar: {
    pageTitle: "تحويل USDT إلى TRX وشراء طاقة TRON｜سريع وآمن وموثوق",
    toggleLang: "العربية",
    desc: "حتى إذا كان رصيد TRX لديك صفرًا، يمكنك تحويل USDT إلى TRX.",
    energy: "الطاقة:",
    bandwidth: "النطاق الترددي:",
    buyEnergy: "شراء الطاقة",
    flashExchange: "تبادل فوري",
    addressLabel: "عنوان الاستلام",
    connectWallet: "اتصل بالمحفظة للحصول على العنوان",
    addressPlaceholder: "الافتراضي هو عنوان الحساب الحالي",
    buyCount: "عدد عمليات الشراء",
    tip: "إذا لم يكن لدى الطرف الآخر USDT، يرجى الشراء مرتين.",
    btn1: "عملية واحدة",
    btn2: "عمليتان",
    btn5: "5 عمليات",
    btn10: "10 عمليات",
    getEnergy: "الحصول على الطاقة",
    expireTip: "صلاحية الطاقة <span class='text-orange'>ساعة واحدة</span>",
    energyPlaceholder: "قيمة الطاقة",
    finalPriceText: "ادفع فقط <span class='text-green-400' id='final_price'></span> وستوفر <span class='text-gray-500 mr-2' id='origin_price'></span>",
    purchaseBtn: "شراء الطاقة",
    inputAmountPlaceholder: "أدخل الكمية",
    outputAmountPlaceholder: "الكمية المتوقعة المستلمة",
    payText: "ستدفع فقط",
    saveText: "سوف توفر",
    payLabel: "الدفع",
    receiveLabel: "الاستلام",
    exchangeNow: "تبادل الآن",
    chooseWallet: "اختر المحفظة",
    scanToLogin: "امسح لتسجيل الدخول",
    confirmOrder: "تأكيد الطلب",
    paymentAddress: "عنوان الدفع:",
    receiveAddress: "عنوان الاستلام:",
    energyAmount: "الطاقة المستأجرة:",
    paymentAmount: "المبلغ المدفوع:",
    confirmPay: "ادفع الآن",
    cancel: "إلغاء",
    closeButtonText: "إغلاق",
    partners: "الشركاء",
    contactUs: "اتصل بنا",
    descsspan: "عدم الإظهار مرة أخرى",
    exchangeRate: "سعر الصرف",
    energyFee: "رسوم الطاقة",
    fee: "الرسوم",
    payment: "المبلغ المطلوب",
    receiveAmount: "الكمية المستلمة:",
    freeEnergy: "طاقة مجانية:",
    freeOfCharge: "بدون رسوم:",
    waiting: "<span class='warning-icon'></span>يرجى عدم إغلاق الصفحة<br>يتم الآن معالجة الطلب، يرجى الانتظار...",
    additionalTextPurchase: "يرجى استخدام الطاقة خلال 10 دقائق لتجنب انتهاء صلاحيتها.",
    additionalTextSwap: "العقد مدقق أمنياً. يمكنك التوقيع بثقة.",
    usdtMinAmount: "الحد الأدنى للمعاملة هو 5 USDT",
    trxMinAmount: "الحد الأدنى للمعاملة هو 22 TRX",
    walletconnecting: "يتم الاتصال بالمحفظة، يرجى الانتظار...",
    loadingText: "<div class='waitloader'></div>يرجى الانتظار...",
    urlToCopy: "تم نسخ الرابط. يرجى لصقه في المتصفح المدمج في المحفظة لفتحه",
    alertTitle: "تنبيه أمني",
    alertDescription: "أبلغ العديد من المستخدمين عن مواقع احتيالية تقلد واجهتنا. يرجى توخي الحذر لتجنب الوقوع ضحية للاحتيال.",
    alertDomainLabel: "نطاقنا الرسمي الوحيد هو:",
    alertButton: "أفهم",
      instructionFaqTitle: "إرشادات الاستخدام والأسئلة الشائعة",
      faqQuestion1: "1. هل الاتصال بالمحفظة آمن؟",
      faqAnswer1: "نعم، الاتصال آمن. يتم فقط قراءة عنوان محفظتك، وتبقى أصولك تحت سيطرتك الكاملة. جميع العمليات تتطلب توقيعًا يدويًا.",
      faqQuestion2: "2. ما هي المحافظ المدعومة؟",
      faqAnswer2: "ندعم جميع المحافظ الرئيسية على شبكة TRON مثل TronLink وTrust Wallet وimToken وغيرها التي تدعم TRC-20.",
      faqQuestion3: "3. هل أحتاج إلى التسجيل أو التحقق من الهوية؟",
      faqAnswer3: "لا، الخدمة لامركزية بالكامل ولا تتطلب تسجيلًا أو تقديم بيانات شخصية.",
      faqQuestion4: "4. هل هذه منصة احتجاز؟",
      faqAnswer4: "لا، الأداة غير احتجازية وكل العمليات تتم مباشرة على شبكة TRON، والأصول تبقى في محفظتك ما لم توقع.",
      faqQuestion5: "5. كم يستغرق إتمام العملية؟",
      faqAnswer5: "غالبًا ما تكتمل المعاملات خلال 6 إلى 15 ثانية. تم تحسين النظام ليكون سريعًا ومستقرًا على شبكة TRON.",
    message: {
      installWallet: (walletName) => `يرجى التأكد من تثبيت تطبيق ${walletName}`,
      invalidPaymentAddress: "عنوان الدفع غير صالح! يرجى إعادة الاتصال بالمحفظة",
      invalidReceiveAddress: "عنوان الاستلام غير صالح! يرجى إدخال عنوان TRON صحيح",
      insufficientBalance: "الرصيد غير كافٍ",
      userCancelled: "قام المستخدم بإلغاء التوقيع",
      serverError: "حدث خطأ في بيانات الخادم!",
      paymentSuccess: "تم الدفع بنجاح!",
      paymentFailure: "فشل في الدفع",
      paymentError: "حدث خطأ أثناء عملية الدفع، يرجى التحقق من المحفظة.",
      approveError: "يرجى استخدام الحد الافتراضي، وإلا لن تتم المعاملة تلقائيًا.",
      txExpired: "انتهت صلاحية المعاملة. يرجى إجراء معاملة جديدة.",
      orderCancelled: "تم إلغاء الطلب"
    }
  },
  hi: {
    pageTitle: "USDT से TRX और TRON ऊर्जा खरीदें｜तेज़, सुरक्षित, भरोसेमंद",
    toggleLang: "हिन्दी",
    desc: "भले ही आपका TRX बैलेंस 0 हो, आप USDT को TRX में स्वैप कर सकते हैं।",
    energy: "ऊर्जा:",
    bandwidth: "बैंडविड्थ:",
    buyEnergy: "ऊर्जा खरीदें",
    flashExchange: "त्वरित एक्सचेंज",
    addressLabel: "प्राप्त करने का पता",
    connectWallet: "वॉलेट कनेक्ट करें और पता प्राप्त करें",
    addressPlaceholder: "डिफ़ॉल्ट रूप से वर्तमान खाता पता",
    buyCount: "खरीद की गिनती",
    tip: "यदि दूसरे पक्ष के पास USDT नहीं है, तो कृपया 2 बार खरीदें।",
    btn1: "1 बार",
    btn2: "2 बार",
    btn5: "5 बार",
    btn10: "10 बार",
    getEnergy: "ऊर्जा प्राप्त करें",
    expireTip: "ऊर्जा की वैधता <span class='text-orange'>1 घंटे</span>",
    energyPlaceholder: "ऊर्जा मान",
    finalPriceText: "आपको केवल <span class='text-green-400' id='final_price'></span> भुगतान करना है, बचत <span class='text-gray-500 mr-2' id='origin_price'></span>",
    purchaseBtn: "ऊर्जा खरीदें",
    inputAmountPlaceholder: "कृपया मात्रा दर्ज करें",
    outputAmountPlaceholder: "अनुमानित प्राप्त राशि",
    payText: "आपको केवल भुगतान करना है",
    saveText: "आपकी बचत",
    payLabel: "भुगतान करें",
    receiveLabel: "प्राप्त करें",
    exchangeNow: "अब एक्सचेंज करें",
    chooseWallet: "वॉलेट चुनें",
    scanToLogin: "QR कोड स्कैन करें",
    confirmOrder: "ऑर्डर की पुष्टि करें",
    paymentAddress: "भुगतान पता:",
    receiveAddress: "प्राप्त पता:",
    energyAmount: "किराए की ऊर्जा:",
    paymentAmount: "भुगतान राशि:",
    confirmPay: "भुगतान करें",
    cancel: "रद्द करें",
    closeButtonText: "बंद करें",
    partners: "साझेदार",
    contactUs: "संपर्क करें",
    descsspan: "फिर से न दिखाएं",
    exchangeRate: "विनिमय दर",
    energyFee: "ऊर्जा शुल्क",
    fee: "शुल्क",
    payment: "भुगतान करना",
    receiveAmount: "प्राप्त राशि:",
    freeEnergy: "मुफ्त ऊर्जा:",
    freeOfCharge: "शुल्क मुक्त:",
    waiting: "<span class='warning-icon'></span>कृपया पेज बंद न करें<br>ऑर्डर संसाधित हो रहा है, कृपया प्रतीक्षा करें...",
    additionalTextPurchase: "कृपया 10 मिनट के भीतर ऊर्जा का उपयोग करें, अन्यथा यह अमान्य हो जाएगी।",
    additionalTextSwap: "अनुबंध सुरक्षित रूप से ऑडिट किया गया है, आप सुरक्षित रूप से साइन कर सकते हैं।",
    usdtMinAmount: "न्यूनतम लेनदेन राशि 5 USDT है",
    trxMinAmount: "न्यूनतम लेनदेन राशि 22 TRX है",
    walletconnecting: "वॉलेट कनेक्ट किया जा रहा है, कृपया प्रतीक्षा करें...",
    loadingText: "<div class='waitloader'></div>कृपया प्रतीक्षा करें...",
    urlToCopy: "URL कॉपी हो गया है। कृपया इसे वॉलेट के इन-बिल्ट ब्राउज़र में पेस्ट करें",
    alertTitle: "सुरक्षा चेतावनी",
    alertDescription: "कई उपयोगकर्ताओं ने उन वेबसाइटों की रिपोर्ट की है जो हमारे इंटरफ़ेस की नकल कर रही हैं। कृपया सतर्क रहें और किसी भी धोखाधड़ी से बचें।",
    alertDomainLabel: "हमारा एकमात्र आधिकारिक डोमेन है:",
    alertButton: "मैं समझ गया",
      instructionFaqTitle: "प्रयोग निर्देश और सामान्य प्रश्न",
      faqQuestion1: "1. क्या वॉलेट कनेक्ट करना सुरक्षित है?",
      faqAnswer1: "हां, यह सुरक्षित है। यह केवल आपके वॉलेट पते को पढ़ता है, आपकी संपत्ति पूरी तरह से आपके नियंत्रण में रहती है। सभी क्रियाएं मैन्युअल रूप से वॉलेट में सत्यापित करनी होती हैं।",
      faqQuestion2: "2. कौन से वॉलेट समर्थित हैं?",
      faqAnswer2: "हम सभी प्रमुख TRON वॉलेट का समर्थन करते हैं जैसे TronLink, Trust Wallet, imToken आदि जो TRC-20 सपोर्ट करते हैं।",
      faqQuestion3: "3. क्या पंजीकरण या KYC की आवश्यकता है?",
      faqAnswer3: "नहीं। यह एक विकेंद्रीकृत सेवा है, कोई पंजीकरण या व्यक्तिगत जानकारी आवश्यक नहीं है।",
      faqQuestion4: "4. क्या यह एक कस्टोडियल प्लेटफ़ॉर्म है?",
      faqAnswer4: "नहीं, यह एक नॉन-कस्टोडियल ऑन-चेन टूल है। आपकी निधियाँ हमेशा आपके वॉलेट में रहती हैं जब तक कि आप हस्ताक्षर करके पुष्टि न करें।",
      faqQuestion5: "5. प्रक्रिया में कितना समय लगता है?",
      faqAnswer5: "अधिकांश लेन-देन 6–15 सेकंड में पूरे हो जाते हैं, यह TRON नेटवर्क के अनुसार अनुकूलित है।",
    message: {
      installWallet: (walletName) => `${walletName} ऐप इंस्टॉल करना सुनिश्चित करें`,
      invalidPaymentAddress: "भुगतान पता अमान्य है! कृपया वॉलेट को फिर से कनेक्ट करें",
      invalidReceiveAddress: "प्राप्त करने का पता अमान्य है! कृपया एक वैध TRON पता दर्ज करें",
      insufficientBalance: "उपयोगकर्ता का बैलेंस अपर्याप्त है",
      userCancelled: "उपयोगकर्ता ने हस्ताक्षर रद्द किया",
      serverError: "सर्वर से डेटा त्रुटिपूर्ण है!",
      paymentSuccess: "भुगतान सफल!",
      paymentFailure: "भुगतान विफल रहा",
      paymentError: "भुगतान के दौरान त्रुटि हुई, कृपया वॉलेट की स्थिति जांचें।",
      approveError: "कृपया डिफ़ॉल्ट सीमा का उपयोग करें, अन्यथा स्वचालित लेन-देन पूरा नहीं होगा।",
      txExpired: "लेनदेन की समयसीमा समाप्त हो गई है। कृपया एक नया शुरू करें।",
      orderCancelled: "ऑर्डर रद्द कर दिया गया है"
    }
  },
  en: {
    pageTitle: "USDT to TRX Conversion & TRON Energy Purchase | Fast, Secure, Reliable",
    toggleLang: "EN",
    desc: "Even if your TRX balance is 0, you can still swap USDT to TRX.",
    energy: "Energy : ",
    bandwidth: "Bandwidth : ",
    buyEnergy: "Buy Energy",
    flashExchange: "USDT ⇄ TRX ",
    addressLabel: "Receiving Address",
    connectWallet: "Connect Wallet to Get Address",
    addressPlaceholder: "Default is current wallet address",
    buyCount: "Quantity",
    tip: "Select 2× if the recipient has no USDT.",
    btn1: "1x",
    btn2: "2x",
    btn5: "5x",
    btn10: "10x",
    getEnergy: "Energy Obtained",
    expireTip: "Energy is valid for <span class='text-orange'>24 hours</span>.",
    energyPlaceholder: "Energy Value",
    finalPriceText: "You only pay <span class='text-green-400' id='final_price'></span> saving you <span class='text-gray-500 mr-2' id='origin_price'></span>",
    purchaseBtn: "Buy Energy",
    inputAmountPlaceholder: "Enter amount",
    outputAmountPlaceholder: "Expected amount",
    payText: "Amount to Pay",
    saveText: "You will save",
    payLabel: "Pay",
    receiveLabel: "Receive",
    exchangeNow: "Exchange Now",
    chooseWallet: "Choose Wallet",
    scanToLogin: "Scan to Login",
    confirmOrder: "Order Confirmation",
    paymentAddress: "Payment Address : ",
    receiveAddress: "Receive Address : ",
    energyAmount: "Energy Amount : ",
    paymentAmount: "Amount to Pay : ",
    closeButtonText: "Close",
    confirmPay: "Confirm",
    cancel: "Cancel",
    partners: "Partners",
    contactUs: "Contact Us",
    descsspan: "Don't show again",
    exchangeRate: 'Exchange Rate',
    energyFee: 'Energy Fee',
    fee: 'Fee',
    payment: 'Amount to Pay',
    receiveAmount: 'Receive Amount : ',
    freeEnergy: 'Free Energy : ',
    freeOfCharge: 'Free of Charge : ',
    waiting: "<span class='warning-icon'></span>Please do not close the page<br>Your order is being processed, please wait...",
    additionalTextPurchase: "Please use the energy within 10 minutes to avoid expiration.",
    additionalTextSwap: "The contract has been audited. You can sign with confidence.",
    usdtMinAmount: "Minimum transaction amount is 5 USDT",
    trxMinAmount: "Minimum transaction amount is 22 TRX",
    walletconnecting: "Connecting wallet, please wait...",
    loadingText: "<div class='waitloader'></div>Please wait...",
    urlToCopy: "URL copied. Please paste it into the wallet's built-in browser to open",
    alertTitle: "Security Alert",
    alertDescription: "Multiple users have recently reported fraudulent websites imitating our interface. Please be extra cautious and avoid falling victim to scams.",
    alertDomainLabel: "Our only official domain is:",
    alertButton: "I understand",
      instructionFaqTitle: "User Guide & FAQ",
      faqQuestion1: "1. Is it safe to connect my wallet?",
      faqAnswer1: "Yes. Connecting only reads your wallet address. You remain in full control of your assets and must approve all actions manually via signature.",
      faqQuestion2: "2. Which wallets are supported?",
      faqAnswer2: "We support all major TRON wallets, including TronLink, Trust Wallet, imToken, and any wallet that supports TRC-20 tokens.",
      faqQuestion3: "3. Do I need to register or complete KYC?",
      faqAnswer3: "No registration or KYC is required. This platform is fully decentralized and does not collect any personal information.",
      faqQuestion4: "4. Is this a custodial service?",
      faqAnswer4: "No. This is a non-custodial on-chain tool. All operations are executed directly on the TRON blockchain, and your assets stay in your wallet unless you sign to confirm.",
      faqQuestion5: "5. How long does the process take?",
      faqAnswer5: "Most operations are completed within 6–15 seconds. The system is optimized for speed and reliability on the TRON network.",
    message: {
      installWallet: (walletName) => `Please confirm you have installed the ${walletName} app`,
      invalidPaymentAddress: "Invalid payment address! Please reconnect your wallet",
      invalidReceiveAddress: "Invalid receive address! Please enter a valid TRON address",
      insufficientBalance: "Insufficient balance in your account",
      userCancelled: "User cancelled the signature",
      serverError: "Server returned an error!",
      paymentSuccess: "Payment successful!",
      paymentFailure: "Payment failed",
      paymentError: "An error occurred during payment, please check wallet status",
      approveError: "Please use the default allowance, otherwise the automatic transaction cannot be completed.",
      txExpired: "The transaction has expired. Please initiate a new one.",
      orderCancelled: "Order has been cancelled"
    }
  }
};

const supportedLanguages = Object.keys(translations);
let currentLang = localStorage.getItem('language');

if (!currentLang || !supportedLanguages.includes(currentLang)) {
  currentLang = 'en';
  localStorage.setItem('language', 'en');
}

document.addEventListener('DOMContentLoaded', () => {
  updateLanguage();

  const toggleBtn = document.getElementById('language-select-toggle');
  const optionsBox = document.getElementById('language-options');

  // 设置默认按钮文字
  const currentOption = document.querySelector(`[data-lang="${currentLang}"]`);
  if (toggleBtn && currentOption) {
    toggleBtn.textContent = currentOption.textContent;
  }

  // 展开或收起语言菜单
  toggleBtn?.addEventListener('click', () => {
    optionsBox.classList.toggle('hidden');
  });

  // 点击语言选项进行切换
  optionsBox.querySelectorAll('[data-lang]').forEach(item => {
    item.addEventListener('click', () => {
      const lang = item.getAttribute('data-lang');
      if (!translations[lang]) return;

      currentLang = lang;
      localStorage.setItem('language', lang);
      updateLanguage();

      // 更新按钮显示文字
      toggleBtn.textContent = item.textContent;
      optionsBox.classList.add('hidden');
    });
  });

  // 点击其他区域收起菜单
  document.addEventListener('click', (e) => {
    if (!document.getElementById('language-switcher').contains(e.target)) {
      optionsBox.classList.add('hidden');
    }
  });
});



function updateLanguage() {
  const dict = translations[currentLang] || {};

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const value = dict[key];
    if (!value) return;

    if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
      el.placeholder = value;
    } else {
      el.innerHTML = value;
    }
  });

  document.documentElement.lang = currentLang;

  // 语言切换按钮（如存在 #language-toggle）
  const toggleLangBtn = document.getElementById('language-toggle');
  if (toggleLangBtn) {
    toggleLangBtn.textContent = currentLang === 'zh' ? 'English' : '中文';
  }

  // 页面标题更新
  if (dict.pageTitle) {
    document.title = dict.pageTitle;
  }
}

